### ISSUE TITLE
Put expose classes at an independent package

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PyFilesystem/pyfilesystem#112]
```
Expose classes adds dependencies for Django and others when they are not always 
necesary. I propose to put it at an independent 'expose' egg/deb package being 
the PyFilesystem core a dependency of it.
```

Original issue reported on code.google.com by `piranna` on 2 Mar 2012 at 9:40

**Comment by jwmullally** [comment]
Is there any plan to do this for the new rewrite https://github.com/PyFilesystem/pyfilesystem2 ?

If not officially, then would you mind people making a minimal "fs-base" package that will be kept in sync with PyFilesystem versions?

Having dependencies like django and boto make this library difficult to use in large development environments. It should also simplify development and packaging of filesystems by seperate teams. PyFilesystem maintainers don't need to worry about API changing breaking consumers because thats what pypi requirements.txt versions are for :)

**Comment by willmcgugan** [comment]
Yes, that's the plan! Pyfilesystem2 will contain filesystems that can be implemented with the stdlib only. Other filesystems will be in namespaces packages, so you can `pip install fs.s3fs` etc.

**Comment by jwmullally** [comment]
Excellent!
