### ISSUE TITLE
Is Python3 supported?

### ISSUE THREAD

**Issue by DamienCassou** [PyFilesystem/pyfilesystem#246]
Could you please tell in the README if Pyhon3 is supported and to what extent? I'm trying to find the cause of some errors in [nixpkgs](http://nixos.org/).

**Comment by DamienCassou** [comment]
Or at least here :-). Thanks

**Comment by lurch** [comment]
http://docs.pyfilesystem.org/en/latest/releasenotes.html  :-)
(or the bottom of https://pypi.python.org/pypi/fs/0.5.4 or https://github.com/PyFilesystem/pyfilesystem/blob/master/tox.ini )

IIRC there are a few small parts that don't work with Python3 (due to dependent-libraries not supporting Py3), but the majority of PyFilesystem should be fine.

**Comment by DamienCassou** [comment]
Some of your source code is not python3 compatible as far as I can tell reading https://docs.python.org/2/tutorial/errors.html#handling-exceptions. For example

https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/errors.py#L220

**Comment by DamienCassou** [comment]
We are discussing about this at https://github.com/NixOS/nixpkgs/pull/13066#issuecomment-185202862

**Comment by lurch** [comment]
I guess this can be closed now?

**Comment by DamienCassou** [comment]
yes, thanks.
